apiVersion: v1
kind: Service
metadata:
  name: {{ include "mqtt.fullname" . }}
  labels:
{{ include "mqtt.labels" . | indent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
    - port: 1883
      targetPort: default
      protocol: TCP
      name: default
    - port: 9001
      targetPort: websocket
      protocol: TCP
      name: websocket
  selector:
    app.kubernetes.io/name: {{ include "mqtt.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
