# Default values for pentair2mqtt.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: cbschuld/pentair-screenlogic
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

env:
  SCREENLOGICIP: 10.252.100.60
  MQTTIP: mqtt-mosquitto.home-automation.svc.production.local
  MQTTPORT: 1883
  MQTTUSER: ""
  MQTTPASS: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
