apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pentair2mqtt.fullname" . }}
  labels:
    {{- include "pentair2mqtt.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "pentair2mqtt.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "pentair2mqtt.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.env }}
      env:
        {{- range $k, $v := . }}
          {{- $name := $k }}
          {{- $value := $v }}
          {{- if kindIs "int" $name }}
            {{- $name = required "environment variables as a list of maps require a name field" $value.name }}
          {{- end }}
        - name: {{ quote $name }}
          {{- if kindIs "map" $value -}}
            {{- if hasKey $value "value" }}
                {{- $value = $value.value -}}
            {{- else if hasKey $value "valueFrom" }}
              {{- toYaml $value | nindent 6 }}
            {{- else }}
              {{- dict "valueFrom" $value | toYaml | nindent 6 }}
            {{- end }}
          {{- end }}
          {{- if not (kindIs "map" $value) }}
            {{- if kindIs "string" $value }}
              {{- $value = tpl $value $ }}
            {{- end }}
          value: {{ quote $value }}
          {{- end }}
        {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
